port: 8888
runmode: debug

db:
  host: 127.0.0.1
  port: 3306
  user: root
  pass: 123456
  name: bumblebee_basic
  charset: utf8
  idleConns: 20
  openConns: 50

redis:
  host: 127.0.0.1
  port: 6379
  db: 11
  pass: ""

rpc:
  host: 127.0.0.1
  port: 9311