port: 8008
runmode: debug

db:
  host: 127.0.0.1
  port: 3306
  user: root
  pass: 123456
  name: bumblebee_basic
  charset: utf8
  idleConns: 10
  openConns: 50

redis:
  host: 127.0.0.1
  port: 6379
  db: 11
  pass: ""

nsq:
  host: 127.0.0.1
  port: 4150

nsqlookupd:
  host: 127.0.0.1
  port: 4161