// Code generated by protoc-gen-go. DO NOT EDIT.
// source: gateway.proto

package gateway

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type CallPayListReq struct {
	AppID                int64    `protobuf:"varint,1,opt,name=appID,proto3" json:"appID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CallPayListReq) Reset()         { *m = CallPayListReq{} }
func (m *CallPayListReq) String() string { return proto.CompactTextString(m) }
func (*CallPayListReq) ProtoMessage()    {}
func (*CallPayListReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_gateway_2100ff96c5e28d84, []int{0}
}
func (m *CallPayListReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CallPayListReq.Unmarshal(m, b)
}
func (m *CallPayListReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CallPayListReq.Marshal(b, m, deterministic)
}
func (dst *CallPayListReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CallPayListReq.Merge(dst, src)
}
func (m *CallPayListReq) XXX_Size() int {
	return xxx_messageInfo_CallPayListReq.Size(m)
}
func (m *CallPayListReq) XXX_DiscardUnknown() {
	xxx_messageInfo_CallPayListReq.DiscardUnknown(m)
}

var xxx_messageInfo_CallPayListReq proto.InternalMessageInfo

func (m *CallPayListReq) GetAppID() int64 {
	if m != nil {
		return m.AppID
	}
	return 0
}

type CallPayListRep struct {
	Code                 string     `protobuf:"bytes,1,opt,name=code,proto3" json:"code,omitempty"`
	Message              string     `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	PayList              []*PayItem `protobuf:"bytes,3,rep,name=payList,proto3" json:"payList,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *CallPayListRep) Reset()         { *m = CallPayListRep{} }
func (m *CallPayListRep) String() string { return proto.CompactTextString(m) }
func (*CallPayListRep) ProtoMessage()    {}
func (*CallPayListRep) Descriptor() ([]byte, []int) {
	return fileDescriptor_gateway_2100ff96c5e28d84, []int{1}
}
func (m *CallPayListRep) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CallPayListRep.Unmarshal(m, b)
}
func (m *CallPayListRep) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CallPayListRep.Marshal(b, m, deterministic)
}
func (dst *CallPayListRep) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CallPayListRep.Merge(dst, src)
}
func (m *CallPayListRep) XXX_Size() int {
	return xxx_messageInfo_CallPayListRep.Size(m)
}
func (m *CallPayListRep) XXX_DiscardUnknown() {
	xxx_messageInfo_CallPayListRep.DiscardUnknown(m)
}

var xxx_messageInfo_CallPayListRep proto.InternalMessageInfo

func (m *CallPayListRep) GetCode() string {
	if m != nil {
		return m.Code
	}
	return ""
}

func (m *CallPayListRep) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func (m *CallPayListRep) GetPayList() []*PayItem {
	if m != nil {
		return m.PayList
	}
	return nil
}

type PayItem struct {
	Id                   string      `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name                 string      `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Icon                 string      `protobuf:"bytes,3,opt,name=icon,proto3" json:"icon,omitempty"`
	Status               int64       `protobuf:"varint,4,opt,name=status,proto3" json:"status,omitempty"`
	TypeList             []*TypeItem `protobuf:"bytes,5,rep,name=typeList,proto3" json:"typeList,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *PayItem) Reset()         { *m = PayItem{} }
func (m *PayItem) String() string { return proto.CompactTextString(m) }
func (*PayItem) ProtoMessage()    {}
func (*PayItem) Descriptor() ([]byte, []int) {
	return fileDescriptor_gateway_2100ff96c5e28d84, []int{2}
}
func (m *PayItem) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PayItem.Unmarshal(m, b)
}
func (m *PayItem) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PayItem.Marshal(b, m, deterministic)
}
func (dst *PayItem) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PayItem.Merge(dst, src)
}
func (m *PayItem) XXX_Size() int {
	return xxx_messageInfo_PayItem.Size(m)
}
func (m *PayItem) XXX_DiscardUnknown() {
	xxx_messageInfo_PayItem.DiscardUnknown(m)
}

var xxx_messageInfo_PayItem proto.InternalMessageInfo

func (m *PayItem) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *PayItem) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *PayItem) GetIcon() string {
	if m != nil {
		return m.Icon
	}
	return ""
}

func (m *PayItem) GetStatus() int64 {
	if m != nil {
		return m.Status
	}
	return 0
}

func (m *PayItem) GetTypeList() []*TypeItem {
	if m != nil {
		return m.TypeList
	}
	return nil
}

type TypeItem struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Icon                 string   `protobuf:"bytes,3,opt,name=icon,proto3" json:"icon,omitempty"`
	Status               int64    `protobuf:"varint,4,opt,name=status,proto3" json:"status,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TypeItem) Reset()         { *m = TypeItem{} }
func (m *TypeItem) String() string { return proto.CompactTextString(m) }
func (*TypeItem) ProtoMessage()    {}
func (*TypeItem) Descriptor() ([]byte, []int) {
	return fileDescriptor_gateway_2100ff96c5e28d84, []int{3}
}
func (m *TypeItem) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TypeItem.Unmarshal(m, b)
}
func (m *TypeItem) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TypeItem.Marshal(b, m, deterministic)
}
func (dst *TypeItem) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TypeItem.Merge(dst, src)
}
func (m *TypeItem) XXX_Size() int {
	return xxx_messageInfo_TypeItem.Size(m)
}
func (m *TypeItem) XXX_DiscardUnknown() {
	xxx_messageInfo_TypeItem.DiscardUnknown(m)
}

var xxx_messageInfo_TypeItem proto.InternalMessageInfo

func (m *TypeItem) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *TypeItem) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *TypeItem) GetIcon() string {
	if m != nil {
		return m.Icon
	}
	return ""
}

func (m *TypeItem) GetStatus() int64 {
	if m != nil {
		return m.Status
	}
	return 0
}

func init() {
	proto.RegisterType((*CallPayListReq)(nil), "gateway.CallPayListReq")
	proto.RegisterType((*CallPayListRep)(nil), "gateway.CallPayListRep")
	proto.RegisterType((*PayItem)(nil), "gateway.PayItem")
	proto.RegisterType((*TypeItem)(nil), "gateway.TypeItem")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// PayCenterSrvClient is the client API for PayCenterSrv service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type PayCenterSrvClient interface {
	CallPayList(ctx context.Context, in *CallPayListReq, opts ...grpc.CallOption) (*CallPayListRep, error)
}

type payCenterSrvClient struct {
	cc *grpc.ClientConn
}

func NewPayCenterSrvClient(cc *grpc.ClientConn) PayCenterSrvClient {
	return &payCenterSrvClient{cc}
}

func (c *payCenterSrvClient) CallPayList(ctx context.Context, in *CallPayListReq, opts ...grpc.CallOption) (*CallPayListRep, error) {
	out := new(CallPayListRep)
	err := c.cc.Invoke(ctx, "/gateway.PayCenterSrv/CallPayList", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PayCenterSrvServer is the server API for PayCenterSrv service.
type PayCenterSrvServer interface {
	CallPayList(context.Context, *CallPayListReq) (*CallPayListRep, error)
}

func RegisterPayCenterSrvServer(s *grpc.Server, srv PayCenterSrvServer) {
	s.RegisterService(&_PayCenterSrv_serviceDesc, srv)
}

func _PayCenterSrv_CallPayList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CallPayListReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PayCenterSrvServer).CallPayList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/gateway.PayCenterSrv/CallPayList",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PayCenterSrvServer).CallPayList(ctx, req.(*CallPayListReq))
	}
	return interceptor(ctx, in, info, handler)
}

var _PayCenterSrv_serviceDesc = grpc.ServiceDesc{
	ServiceName: "gateway.PayCenterSrv",
	HandlerType: (*PayCenterSrvServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CallPayList",
			Handler:    _PayCenterSrv_CallPayList_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "gateway.proto",
}

func init() { proto.RegisterFile("gateway.proto", fileDescriptor_gateway_2100ff96c5e28d84) }

var fileDescriptor_gateway_2100ff96c5e28d84 = []byte{
	// 266 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xac, 0x91, 0x41, 0x4b, 0xc3, 0x40,
	0x10, 0x85, 0x49, 0xd2, 0x36, 0x75, 0xaa, 0x45, 0x07, 0xd1, 0xc5, 0x53, 0xc9, 0x41, 0x8a, 0x60,
	0x0f, 0xf5, 0x07, 0x78, 0xa8, 0x97, 0x82, 0x60, 0x88, 0x9e, 0xbc, 0x8d, 0xcd, 0x50, 0x22, 0x4d,
	0xb2, 0x26, 0xab, 0xb2, 0xff, 0xc0, 0x9f, 0x2d, 0x99, 0x64, 0x83, 0x0a, 0xde, 0x7a, 0x7b, 0xef,
	0xe5, 0x65, 0xe7, 0xdb, 0x1d, 0x38, 0xda, 0x92, 0xe1, 0x4f, 0xb2, 0x0b, 0x5d, 0x95, 0xa6, 0xc4,
	0xb0, 0xb3, 0xd1, 0x25, 0x4c, 0x57, 0xb4, 0xdb, 0xc5, 0x64, 0xef, 0xb3, 0xda, 0x24, 0xfc, 0x86,
	0xa7, 0x30, 0x24, 0xad, 0xd7, 0x77, 0xca, 0x9b, 0x79, 0xf3, 0x20, 0x69, 0x4d, 0xf4, 0xfa, 0xa7,
	0xa7, 0x11, 0x61, 0xb0, 0x29, 0x53, 0x96, 0xda, 0x41, 0x22, 0x1a, 0x15, 0x84, 0x39, 0xd7, 0x35,
	0x6d, 0x59, 0xf9, 0x12, 0x3b, 0x8b, 0x57, 0x10, 0xea, 0xf6, 0x5f, 0x15, 0xcc, 0x82, 0xf9, 0x64,
	0x79, 0xbc, 0x70, 0x44, 0x31, 0xd9, 0xb5, 0xe1, 0x3c, 0x71, 0x85, 0xe8, 0xcb, 0x83, 0xb0, 0x0b,
	0x71, 0x0a, 0x7e, 0x96, 0x76, 0x33, 0xfc, 0x2c, 0x6d, 0xa6, 0x16, 0x94, 0xbb, 0xe3, 0x45, 0x37,
	0x59, 0xb6, 0x29, 0x0b, 0x15, 0xb4, 0x59, 0xa3, 0xf1, 0x0c, 0x46, 0xb5, 0x21, 0xf3, 0x5e, 0xab,
	0x81, 0x5c, 0xa3, 0x73, 0x78, 0x0d, 0x63, 0x63, 0x35, 0x0b, 0xc8, 0x50, 0x40, 0x4e, 0x7a, 0x90,
	0x27, 0xab, 0x59, 0x48, 0xfa, 0x4a, 0xf4, 0x0c, 0x63, 0x97, 0xee, 0x1b, 0x65, 0xf9, 0x00, 0x87,
	0x31, 0xd9, 0x15, 0x17, 0x86, 0xab, 0xc7, 0xea, 0x03, 0x6f, 0x61, 0xf2, 0xe3, 0x89, 0xf1, 0xbc,
	0xe7, 0xfa, 0xbd, 0xa0, 0x8b, 0x7f, 0x3e, 0xe8, 0x97, 0x91, 0xec, 0xf6, 0xe6, 0x3b, 0x00, 0x00,
	0xff, 0xff, 0xe6, 0xd4, 0x96, 0x4e, 0xec, 0x01, 0x00, 0x00,
}
